# Generated by Django 3.1.7 on 2021-03-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_or_url', models.CharField(max_length=255, unique=True)),
                ('ip', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('continent_code', models.CharField(max_length=255)),
                ('continent_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('region_code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.JSONField(null=True)),
                ('time_zone', models.JSONField(null=True)),
                ('currency', models.JSONField(null=True)),
                ('connection', models.JSONField(null=True)),
            ],
        ),
    ]
